[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.9" }
rojo = { source = "Roblox/rojo-rbx-rojo", version = "7.3.0" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.25.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "=0.16.0" }
evaluate = { source = "roblox/evaluate", version = "0.2.1" }
