[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.25" }
rojo = { source = "Roblox/rojo-rbx-rojo", version = "7.3.0" }
selene = { source = "Roblox/Kampfkarren-selene", version = "=0.27.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "=0.17.1" }
evaluate = { source = "Roblox/evaluate", version = "=0.3.1" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "=5.8.0" }
