[package]
name = "ApolloClient"
version = "0.1.0"
author = "Roblox"
content_root = "src"

[dependencies]
Roact = { git = "https://github.com/roblox/roact-alignment.git", rev = "293eaac" }
GraphQL = { git = "https://github.com/Roblox/graphql-lua.git", branch = "master" }

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@0.7.1"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.1.5"