[package]
name = "ApolloClient"
version = "0.1.0"
author = "Roblox"
content_root = "src"

[dependencies]
React = { git = "https://github.com/roblox/roact-alignment.git", package = "React" }
Shared = { git = "https://github.com/roblox/roact-alignment.git", package = "Shared" }
ReactRoblox = { git = "https://github.com/roblox/roact-alignment.git", package = "ReactRoblox" }
GraphQL = { git = "https://github.com/Roblox/graphql-lua.git", branch = "master" }
LuauPolyfill = "github.com/roblox/luau-polyfill@0.2.1"
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@=1.1.2"
LuauRegExp = "github.com/Roblox/luau-regexp@0.1.0"
GraphQLTag = "github.com/thisdot/graphql-tag-lua@2.12.3"