[package]
name = "ApolloClient"
version = "0.1.0"
author = "Roblox"
content_root = "src"

[dependencies]
Roact = { git = "https://github.com/roblox/roact-alignment.git", package = "React" }
ReactRoblox = { git = "https://github.com/roblox/roact-alignment.git", package = "ReactRoblox" }
GraphQL = { git = "https://github.com/Roblox/graphql-lua.git", branch = "master" }

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@=1.1.2"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.2.0"
