[package]
name = "ApolloClient"
version = "0.1.0"
author = "Roblox"
content_root = "src"

[dependencies]
React = { git = "https://github.com/roblox/roact-alignment.git", package = "React" }
Shared = { git = "https://github.com/roblox/roact-alignment.git", package = "Shared" }
ReactRoblox = { git = "https://github.com/roblox/roact-alignment.git", package = "ReactRoblox" }
GraphQL = { git = "https://github.com/Roblox/graphql-lua.git", rev = "c511c9a3" }
LuauPolyfill = "github.com/roblox/luau-polyfill@0.2.5"
ZenObservable = { git = "https://github.com/roblox/zen-observable-lua.git", rev = "v0.8.15-rc.6" }
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"
LuauRegExp = "github.com/Roblox/luau-regexp@0.1.3"

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@=1.1.2"
GraphQLTag = "github.com/Roblox/graphql-tag-lua@2.12.3"
ReactReconciler = { git = "https://github.com/roblox/roact-alignment.git", package = "ReactReconciler" }
RoactCompat = { git = "https://github.com/roblox/roact-alignment.git", package = "RoactCompat" }
Scheduler = { git = "https://github.com/roblox/roact-alignment.git", package = "Scheduler" }
