[package]
name = "ApolloClient"
version = "0.3.6"
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**", "!testUtils/", "!**/testing/**"]

[dependencies]
React = "github.com/roblox/roact-alignment@17.0.1-rc.16"
GraphQL = "github.com/Roblox/graphql-lua@15.6.0"
GraphQLTag = "github.com/Roblox/graphql-tag-lua@2.12.6"
LuauPolyfill = "github.com/roblox/luau-polyfill@1"
ZenObservable = "github.com/roblox/zen-observable-lua@0.8.16-roblox.0"
Promise = "github.com/roblox/roblox-lua-promise@3.3.0"
LuauRegExp = "github.com/Roblox/luau-regexp@0.2.0"
RobloxRequests = "github.com/thisdot/roblox-requests@0.1.0"

[dev_dependencies]
JestGlobals = { git = "https://github.com/roblox/jest-roblox", rev = "v3.2.2", package = "JestGlobals" }
Jest = { git = "https://github.com/roblox/jest-roblox", rev = "v3.2.2", package = "Jest" }
ReactTestingLibrary = { git = "https://github.com/roblox/react-testing-library-lua.git", rev = "main" }
