[package]
name = "ApolloClient"
version = "0.1.0"
author = "Roblox"
content_root = "src"

[dependencies]
React = "github.com/roblox/roact-alignment@17.0.1-rc.16"
GraphQL = "github.com/Roblox/graphql-lua@15.5.1"
GraphQLTag = "github.com/Roblox/graphql-tag-lua@2.12.6"
LuauPolyfill = "github.com/roblox/luau-polyfill@1"
ZenObservable = "github.com/roblox/zen-observable-lua@0.8.16-roblox.0"
Promise = "github.com/roblox/roblox-lua-promise@3.3.0"
LuauRegExp = "github.com/Roblox/luau-regexp@0.2.0"
RobloxRequests = "github.com/thisdot/roblox-requests@0.1.0"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@3.0.0-rc.0"
Jest = "github.com/roblox/jest-roblox@3.0.0-rc.0"
ReactTestingLibrary = { git = "https://github.com/roblox/react-testing-library-lua.git", rev = "main" }
